# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(565, 651)
        Dialog.setMinimumSize(QtCore.QSize(565, 651))
        Dialog.setMaximumSize(QtCore.QSize(565, 16777215))
        self.FwVersionlabel = QtGui.QLabel(Dialog)
        self.FwVersionlabel.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.FwVersionlabel.setObjectName(_fromUtf8("FwVersionlabel"))
        self.FwVersionlineEdit = QtGui.QLineEdit(Dialog)
        self.FwVersionlineEdit.setGeometry(QtCore.QRect(110, 120, 151, 20))
        self.FwVersionlineEdit.setText(_fromUtf8(""))
        self.FwVersionlineEdit.setFrame(True)
        self.FwVersionlineEdit.setDragEnabled(False)
        self.FwVersionlineEdit.setReadOnly(True)
        self.FwVersionlineEdit.setObjectName(_fromUtf8("FwVersionlineEdit"))
        self.FwUpgradeButton = QtGui.QPushButton(Dialog)
        self.FwUpgradeButton.setGeometry(QtCore.QRect(270, 120, 81, 23))
        self.FwUpgradeButton.setObjectName(_fromUtf8("FwUpgradeButton"))
        self.ResetButton = QtGui.QPushButton(Dialog)
        self.ResetButton.setGeometry(QtCore.QRect(360, 120, 91, 23))
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.UpdateUdiskButton = QtGui.QPushButton(Dialog)
        self.UpdateUdiskButton.setGeometry(QtCore.QRect(360, 390, 91, 23))
        self.UpdateUdiskButton.setObjectName(_fromUtf8("UpdateUdiskButton"))
        self.logEdit = QtGui.QTextEdit(Dialog)
        self.logEdit.setGeometry(QtCore.QRect(20, 450, 531, 161))
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName(_fromUtf8("logEdit"))
        self.Snlabel = QtGui.QLabel(Dialog)
        self.Snlabel.setGeometry(QtCore.QRect(20, 150, 51, 16))
        self.Snlabel.setObjectName(_fromUtf8("Snlabel"))
        self.SnlineEdit = QtGui.QLineEdit(Dialog)
        self.SnlineEdit.setGeometry(QtCore.QRect(110, 150, 151, 21))
        self.SnlineEdit.setText(_fromUtf8(""))
        self.SnlineEdit.setFrame(True)
        self.SnlineEdit.setDragEnabled(False)
        self.SnlineEdit.setReadOnly(False)
        self.SnlineEdit.setObjectName(_fromUtf8("SnlineEdit"))
        self.ResetSnlabel = QtGui.QLabel(Dialog)
        self.ResetSnlabel.setGeometry(QtCore.QRect(20, 180, 91, 20))
        self.ResetSnlabel.setObjectName(_fromUtf8("ResetSnlabel"))
        self.SSIDlabel = QtGui.QLabel(Dialog)
        self.SSIDlabel.setGeometry(QtCore.QRect(20, 210, 71, 20))
        self.SSIDlabel.setObjectName(_fromUtf8("SSIDlabel"))
        self.ResetSnlineEdit = QtGui.QLineEdit(Dialog)
        self.ResetSnlineEdit.setGeometry(QtCore.QRect(110, 180, 151, 21))
        self.ResetSnlineEdit.setText(_fromUtf8(""))
        self.ResetSnlineEdit.setFrame(True)
        self.ResetSnlineEdit.setDragEnabled(False)
        self.ResetSnlineEdit.setReadOnly(False)
        self.ResetSnlineEdit.setObjectName(_fromUtf8("ResetSnlineEdit"))
        self.SetSnButton = QtGui.QPushButton(Dialog)
        self.SetSnButton.setGeometry(QtCore.QRect(270, 150, 81, 23))
        self.SetSnButton.setObjectName(_fromUtf8("SetSnButton"))
        self.SetResetSnButton = QtGui.QPushButton(Dialog)
        self.SetResetSnButton.setGeometry(QtCore.QRect(270, 180, 81, 23))
        self.SetResetSnButton.setObjectName(_fromUtf8("SetResetSnButton"))
        self.SSIDlineEdit = QtGui.QLineEdit(Dialog)
        self.SSIDlineEdit.setGeometry(QtCore.QRect(110, 210, 151, 21))
        self.SSIDlineEdit.setText(_fromUtf8(""))
        self.SSIDlineEdit.setFrame(True)
        self.SSIDlineEdit.setDragEnabled(False)
        self.SSIDlineEdit.setReadOnly(False)
        self.SSIDlineEdit.setObjectName(_fromUtf8("SSIDlineEdit"))
        self.SetSSIDButton = QtGui.QPushButton(Dialog)
        self.SetSSIDButton.setGeometry(QtCore.QRect(270, 210, 81, 23))
        self.SetSSIDButton.setObjectName(_fromUtf8("SetSSIDButton"))
        self.CmdlineEdit = QtGui.QLineEdit(Dialog)
        self.CmdlineEdit.setGeometry(QtCore.QRect(20, 620, 531, 20))
        self.CmdlineEdit.setObjectName(_fromUtf8("CmdlineEdit"))
        self.Passwdlabel = QtGui.QLabel(Dialog)
        self.Passwdlabel.setGeometry(QtCore.QRect(20, 240, 71, 20))
        self.Passwdlabel.setObjectName(_fromUtf8("Passwdlabel"))
        self.PasswdlineEdit = QtGui.QLineEdit(Dialog)
        self.PasswdlineEdit.setGeometry(QtCore.QRect(110, 240, 151, 21))
        self.PasswdlineEdit.setText(_fromUtf8(""))
        self.PasswdlineEdit.setFrame(True)
        self.PasswdlineEdit.setDragEnabled(False)
        self.PasswdlineEdit.setReadOnly(False)
        self.PasswdlineEdit.setObjectName(_fromUtf8("PasswdlineEdit"))
        self.SetPasswdButton = QtGui.QPushButton(Dialog)
        self.SetPasswdButton.setGeometry(QtCore.QRect(270, 240, 81, 23))
        self.SetPasswdButton.setObjectName(_fromUtf8("SetPasswdButton"))
        self.RestartNetworkButton = QtGui.QPushButton(Dialog)
        self.RestartNetworkButton.setGeometry(QtCore.QRect(360, 150, 91, 23))
        self.RestartNetworkButton.setObjectName(_fromUtf8("RestartNetworkButton"))
        self.ClearSqliteButton = QtGui.QPushButton(Dialog)
        self.ClearSqliteButton.setGeometry(QtCore.QRect(460, 120, 91, 23))
        self.ClearSqliteButton.setObjectName(_fromUtf8("ClearSqliteButton"))
        self.WanMaclabel = QtGui.QLabel(Dialog)
        self.WanMaclabel.setGeometry(QtCore.QRect(20, 360, 51, 21))
        self.WanMaclabel.setObjectName(_fromUtf8("WanMaclabel"))
        self.WanMaclineEdit = QtGui.QLineEdit(Dialog)
        self.WanMaclineEdit.setGeometry(QtCore.QRect(110, 360, 151, 21))
        self.WanMaclineEdit.setText(_fromUtf8(""))
        self.WanMaclineEdit.setFrame(True)
        self.WanMaclineEdit.setDragEnabled(False)
        self.WanMaclineEdit.setReadOnly(True)
        self.WanMaclineEdit.setObjectName(_fromUtf8("WanMaclineEdit"))
        self.LanMaclineEdit = QtGui.QLineEdit(Dialog)
        self.LanMaclineEdit.setGeometry(QtCore.QRect(110, 330, 151, 21))
        self.LanMaclineEdit.setText(_fromUtf8(""))
        self.LanMaclineEdit.setFrame(True)
        self.LanMaclineEdit.setDragEnabled(False)
        self.LanMaclineEdit.setReadOnly(True)
        self.LanMaclineEdit.setObjectName(_fromUtf8("LanMaclineEdit"))
        self.LanMaclabel = QtGui.QLabel(Dialog)
        self.LanMaclabel.setGeometry(QtCore.QRect(20, 330, 51, 31))
        self.LanMaclabel.setObjectName(_fromUtf8("LanMaclabel"))
        self.AthMaclabel = QtGui.QLabel(Dialog)
        self.AthMaclabel.setGeometry(QtCore.QRect(20, 300, 51, 21))
        self.AthMaclabel.setObjectName(_fromUtf8("AthMaclabel"))
        self.AthMaclineEdit = QtGui.QLineEdit(Dialog)
        self.AthMaclineEdit.setGeometry(QtCore.QRect(110, 300, 151, 21))
        self.AthMaclineEdit.setText(_fromUtf8(""))
        self.AthMaclineEdit.setFrame(True)
        self.AthMaclineEdit.setDragEnabled(False)
        self.AthMaclineEdit.setReadOnly(False)
        self.AthMaclineEdit.setObjectName(_fromUtf8("AthMaclineEdit"))
        self.WanSSIDlabel = QtGui.QLabel(Dialog)
        self.WanSSIDlabel.setGeometry(QtCore.QRect(20, 270, 71, 20))
        self.WanSSIDlabel.setObjectName(_fromUtf8("WanSSIDlabel"))
        self.WanSSIDlineEdit = QtGui.QLineEdit(Dialog)
        self.WanSSIDlineEdit.setGeometry(QtCore.QRect(110, 270, 151, 21))
        self.WanSSIDlineEdit.setText(_fromUtf8(""))
        self.WanSSIDlineEdit.setFrame(True)
        self.WanSSIDlineEdit.setDragEnabled(False)
        self.WanSSIDlineEdit.setReadOnly(True)
        self.WanSSIDlineEdit.setObjectName(_fromUtf8("WanSSIDlineEdit"))
        self.CheckUDiskButton = QtGui.QPushButton(Dialog)
        self.CheckUDiskButton.setGeometry(QtCore.QRect(360, 360, 91, 23))
        self.CheckUDiskButton.setObjectName(_fromUtf8("CheckUDiskButton"))
        self.UDiskBar = QtGui.QProgressBar(Dialog)
        self.UDiskBar.setGeometry(QtCore.QRect(460, 360, 91, 23))
        self.UDiskBar.setProperty("value", 24)
        self.UDiskBar.setObjectName(_fromUtf8("UDiskBar"))
        self.AppMd5CheckBox = QtGui.QCheckBox(Dialog)
        self.AppMd5CheckBox.setGeometry(QtCore.QRect(460, 390, 91, 21))
        self.AppMd5CheckBox.setObjectName(_fromUtf8("AppMd5CheckBox"))
        self.SetMacButton = QtGui.QPushButton(Dialog)
        self.SetMacButton.setGeometry(QtCore.QRect(270, 300, 41, 81))
        self.SetMacButton.setObjectName(_fromUtf8("SetMacButton"))
        self.SaveLogButton = QtGui.QPushButton(Dialog)
        self.SaveLogButton.setGeometry(QtCore.QRect(460, 150, 91, 23))
        self.SaveLogButton.setObjectName(_fromUtf8("SaveLogButton"))
        self.DebugStatButton = QtGui.QPushButton(Dialog)
        self.DebugStatButton.setGeometry(QtCore.QRect(360, 180, 91, 23))
        self.DebugStatButton.setObjectName(_fromUtf8("DebugStatButton"))
        self.FormatUDiskButton = QtGui.QPushButton(Dialog)
        self.FormatUDiskButton.setGeometry(QtCore.QRect(360, 330, 91, 23))
        self.FormatUDiskButton.setObjectName(_fromUtf8("FormatUDiskButton"))
        self.InitDoneButton = QtGui.QPushButton(Dialog)
        self.InitDoneButton.setGeometry(QtCore.QRect(460, 180, 91, 23))
        self.InitDoneButton.setObjectName(_fromUtf8("InitDoneButton"))
        self.CheckAppButton = QtGui.QPushButton(Dialog)
        self.CheckAppButton.setGeometry(QtCore.QRect(360, 420, 91, 23))
        self.CheckAppButton.setObjectName(_fromUtf8("CheckAppButton"))
        self.WanMaclabel_2 = QtGui.QLabel(Dialog)
        self.WanMaclabel_2.setGeometry(QtCore.QRect(20, 390, 241, 21))
        self.WanMaclabel_2.setObjectName(_fromUtf8("WanMaclabel_2"))
        self.AppLineEdit = QtGui.QLineEdit(Dialog)
        self.AppLineEdit.setGeometry(QtCore.QRect(20, 420, 331, 21))
        self.AppLineEdit.setText(_fromUtf8(""))
        self.AppLineEdit.setFrame(True)
        self.AppLineEdit.setDragEnabled(False)
        self.AppLineEdit.setReadOnly(True)
        self.AppLineEdit.setObjectName(_fromUtf8("AppLineEdit"))
        self.AppButton = QtGui.QPushButton(Dialog)
        self.AppButton.setGeometry(QtCore.QRect(270, 390, 81, 23))
        self.AppButton.setObjectName(_fromUtf8("AppButton"))
        self.DelAppButton = QtGui.QPushButton(Dialog)
        self.DelAppButton.setGeometry(QtCore.QRect(460, 420, 91, 23))
        self.DelAppButton.setObjectName(_fromUtf8("DelAppButton"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 531, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.TargetIPlabel = QtGui.QLabel(self.groupBox)
        self.TargetIPlabel.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.TargetIPlabel.setObjectName(_fromUtf8("TargetIPlabel"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(200, 20, 31, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEditPort = QtGui.QLineEdit(self.groupBox)
        self.lineEditPort.setGeometry(QtCore.QRect(250, 20, 113, 20))
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 51, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditUsername = QtGui.QLineEdit(self.groupBox)
        self.lineEditUsername.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 31, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditPassword = QtGui.QLineEdit(self.groupBox)
        self.lineEditPassword.setGeometry(QtCore.QRect(250, 50, 113, 20))
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.ConnectButton = QtGui.QPushButton(self.groupBox)
        self.ConnectButton.setGeometry(QtCore.QRect(370, 19, 71, 23))
        self.ConnectButton.setFlat(False)
        self.ConnectButton.setObjectName(_fromUtf8("ConnectButton"))
        self.RebootButton = QtGui.QPushButton(self.groupBox)
        self.RebootButton.setGeometry(QtCore.QRect(370, 50, 71, 23))
        self.RebootButton.setObjectName(_fromUtf8("RebootButton"))
        self.HaltButton = QtGui.QPushButton(self.groupBox)
        self.HaltButton.setGeometry(QtCore.QRect(450, 50, 71, 23))
        self.HaltButton.setObjectName(_fromUtf8("HaltButton"))
        self.lineEditIp = QtGui.QLineEdit(self.groupBox)
        self.lineEditIp.setGeometry(QtCore.QRect(70, 20, 113, 20))
        self.lineEditIp.setObjectName(_fromUtf8("lineEditIp"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        Dialog.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.FwVersionlabel.setText(_translate("Dialog", "固件版本", None))
        self.FwUpgradeButton.setText(_translate("Dialog", "升级固件", None))
        self.ResetButton.setText(_translate("Dialog", "恢复出厂设置", None))
        self.UpdateUdiskButton.setText(_translate("Dialog", "更新APP", None))
        self.Snlabel.setText(_translate("Dialog", "序列号", None))
        self.ResetSnlabel.setText(_translate("Dialog", "出厂设置序列号", None))
        self.SSIDlabel.setText(_translate("Dialog", "WIFI名称", None))
        self.SetSnButton.setText(_translate("Dialog", "更改", None))
        self.SetResetSnButton.setText(_translate("Dialog", "更改", None))
        self.SetSSIDButton.setText(_translate("Dialog", "更改", None))
        self.Passwdlabel.setText(_translate("Dialog", "WIFI密码", None))
        self.SetPasswdButton.setText(_translate("Dialog", "更改", None))
        self.RestartNetworkButton.setText(_translate("Dialog", "重启网络", None))
        self.ClearSqliteButton.setText(_translate("Dialog", "清除下载统计", None))
        self.WanMaclabel.setText(_translate("Dialog", "WAN MAC", None))
        self.LanMaclabel.setText(_translate("Dialog", "LAN MAC", None))
        self.AthMaclabel.setText(_translate("Dialog", "WIFI MAC", None))
        self.WanSSIDlabel.setText(_translate("Dialog", "上级WIFI名称", None))
        self.CheckUDiskButton.setText(_translate("Dialog", "检查U盘", None))
        self.AppMd5CheckBox.setText(_translate("Dialog", "MD5校验", None))
        self.SetMacButton.setText(_translate("Dialog", "更改", None))
        self.SaveLogButton.setText(_translate("Dialog", "保存LOG", None))
        self.DebugStatButton.setText(_translate("Dialog", "DEBUG Off", None))
        self.FormatUDiskButton.setText(_translate("Dialog", "格式化U盘", None))
        self.InitDoneButton.setText(_translate("Dialog", "快速设置打开", None))
        self.CheckAppButton.setText(_translate("Dialog", "检查APP文件", None))
        self.WanMaclabel_2.setText(_translate("Dialog", "App包", None))
        self.AppButton.setText(_translate("Dialog", "浏览", None))
        self.DelAppButton.setText(_translate("Dialog", "删除App", None))
        self.groupBox.setTitle(_translate("Dialog", "连接", None))
        self.TargetIPlabel.setText(_translate("Dialog", "设备IP", None))
        self.label.setText(_translate("Dialog", "端口", None))
        self.lineEditPort.setText(_translate("Dialog", "22122", None))
        self.label_2.setText(_translate("Dialog", "用户名", None))
        self.lineEditUsername.setText(_translate("Dialog", "root", None))
        self.label_3.setText(_translate("Dialog", "密码", None))
        self.lineEditPassword.setText(_translate("Dialog", "t0d7r19tdr", None))
        self.ConnectButton.setText(_translate("Dialog", "未连接", None))
        self.RebootButton.setText(_translate("Dialog", "重启", None))
        self.HaltButton.setText(_translate("Dialog", "关机", None))
        self.lineEditIp.setText(_translate("Dialog", "192.168.168.23", None))

