# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.TargetIPlabel = QtGui.QLabel(self.frame)
        self.TargetIPlabel.setObjectName(_fromUtf8("TargetIPlabel"))
        self.horizontalLayout.addWidget(self.TargetIPlabel)
        self.lineEditIp = QtGui.QLineEdit(self.frame)
        self.lineEditIp.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditIp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditIp.setObjectName(_fromUtf8("lineEditIp"))
        self.horizontalLayout.addWidget(self.lineEditIp)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditPort = QtGui.QLineEdit(self.frame)
        self.lineEditPort.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditPort.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.horizontalLayout.addWidget(self.lineEditPort)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditUsername = QtGui.QLineEdit(self.frame)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.horizontalLayout.addWidget(self.lineEditUsername)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditPassword = QtGui.QLineEdit(self.frame)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.horizontalLayout.addWidget(self.lineEditPassword)
        self.ConnectButton = QtGui.QPushButton(self.frame)
        self.ConnectButton.setFlat(False)
        self.ConnectButton.setObjectName(_fromUtf8("ConnectButton"))
        self.horizontalLayout.addWidget(self.ConnectButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_4 = QtGui.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.frame_4)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setAccessibleName(_fromUtf8(""))
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabInfo)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.tabInfo)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.textBrowserInfo = QtGui.QTextBrowser(self.tabInfo)
        self.textBrowserInfo.setStyleSheet(_fromUtf8("border: none;"))
        self.textBrowserInfo.setObjectName(_fromUtf8("textBrowserInfo"))
        self.verticalLayout_4.addWidget(self.textBrowserInfo)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabServerSetting = QtGui.QWidget()
        self.tabServerSetting.setObjectName(_fromUtf8("tabServerSetting"))
        self.formLayoutWidget = QtGui.QWidget(self.tabServerSetting)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 181))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.Label = QtGui.QLabel(self.formLayoutWidget)
        self.Label.setObjectName(_fromUtf8("Label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label)
        self.LineEditOperationIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditOperationIp.setObjectName(_fromUtf8("LineEditOperationIp"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEditOperationIp)
        self.Label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_2)
        self.LineEditOperationPort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditOperationPort.setObjectName(_fromUtf8("LineEditOperationPort"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LineEditOperationPort)
        self.Label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_3.setObjectName(_fromUtf8("Label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_3)
        self.LineEditUpdateIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditUpdateIp.setObjectName(_fromUtf8("LineEditUpdateIp"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LineEditUpdateIp)
        self.Label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_4.setObjectName(_fromUtf8("Label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_4)
        self.LineEditUpdatePort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditUpdatePort.setObjectName(_fromUtf8("LineEditUpdatePort"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LineEditUpdatePort)
        self.LineEditIdCardIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditIdCardIp.setObjectName(_fromUtf8("LineEditIdCardIp"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.LineEditIdCardIp)
        self.LineEditIdCardPort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditIdCardPort.setObjectName(_fromUtf8("LineEditIdCardPort"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.LineEditIdCardPort)
        self.Label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_6.setObjectName(_fromUtf8("Label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_6)
        self.Label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_5.setObjectName(_fromUtf8("Label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_5)
        self.uRLLabel = QtGui.QLabel(self.formLayoutWidget)
        self.uRLLabel.setObjectName(_fromUtf8("uRLLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.uRLLabel)
        self.LineEditLogURL = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditLogURL.setObjectName(_fromUtf8("LineEditLogURL"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.LineEditLogURL)
        self.pushButtonSaveServer = QtGui.QPushButton(self.tabServerSetting)
        self.pushButtonSaveServer.setGeometry(QtCore.QRect(590, 200, 75, 23))
        self.pushButtonSaveServer.setObjectName(_fromUtf8("pushButtonSaveServer"))
        self.pushButtonRefreshServer = QtGui.QPushButton(self.tabServerSetting)
        self.pushButtonRefreshServer.setGeometry(QtCore.QRect(500, 200, 75, 23))
        self.pushButtonRefreshServer.setObjectName(_fromUtf8("pushButtonRefreshServer"))
        self.tabWidget.addTab(self.tabServerSetting, _fromUtf8(""))
        self.tabNetSetting = QtGui.QWidget()
        self.tabNetSetting.setObjectName(_fromUtf8("tabNetSetting"))
        self.tabWidget.addTab(self.tabNetSetting, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.logEdit = QtGui.QTextEdit(self.frame_2)
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName(_fromUtf8("logEdit"))
        self.verticalLayout.addWidget(self.logEdit)
        self.CmdlineEdit = QtGui.QLineEdit(self.frame_2)
        self.CmdlineEdit.setObjectName(_fromUtf8("CmdlineEdit"))
        self.verticalLayout.addWidget(self.CmdlineEdit)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.TargetIPlabel.setText(_translate("MainWindow", "设备IP：", None))
        self.lineEditIp.setText(_translate("MainWindow", "172.16.34.111", None))
        self.label.setText(_translate("MainWindow", "端口：", None))
        self.lineEditPort.setText(_translate("MainWindow", "22", None))
        self.label_2.setText(_translate("MainWindow", "用户名：", None))
        self.lineEditUsername.setText(_translate("MainWindow", "root", None))
        self.label_3.setText(_translate("MainWindow", "密码：", None))
        self.lineEditPassword.setText(_translate("MainWindow", "t0d7r19tdr", None))
        self.ConnectButton.setText(_translate("MainWindow", "未连接", None))
        self.pushButton.setText(_translate("MainWindow", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("MainWindow", "信息", None))
        self.Label.setText(_translate("MainWindow", "业务服务器地址", None))
        self.Label_2.setText(_translate("MainWindow", "业务服务器端口", None))
        self.Label_3.setText(_translate("MainWindow", "升级服务器地址", None))
        self.Label_4.setText(_translate("MainWindow", "升级服务器端口", None))
        self.Label_6.setText(_translate("MainWindow", "身份证服务器端口", None))
        self.Label_5.setText(_translate("MainWindow", "身份证服务器地址", None))
        self.uRLLabel.setText(_translate("MainWindow", "日志服务URL", None))
        self.pushButtonSaveServer.setText(_translate("MainWindow", "保存", None))
        self.pushButtonRefreshServer.setText(_translate("MainWindow", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServerSetting), _translate("MainWindow", "服务器配置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNetSetting), _translate("MainWindow", "网络配置", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.action.setText(_translate("MainWindow", "退出", None))

