# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(915, 575)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, 9, 9, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_4 = QtGui.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textBrowserFlash = QtGui.QTextBrowser(self.frame_4)
        self.textBrowserFlash.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textBrowserFlash.setObjectName(_fromUtf8("textBrowserFlash"))
        self.gridLayout_2.addWidget(self.textBrowserFlash, 3, 0, 1, 15)
        self.pushButtonFirmwareDir = QtGui.QPushButton(self.frame_4)
        self.pushButtonFirmwareDir.setObjectName(_fromUtf8("pushButtonFirmwareDir"))
        self.gridLayout_2.addWidget(self.pushButtonFirmwareDir, 1, 10, 1, 1)
        self.pushButtonFlash = QtGui.QPushButton(self.frame_4)
        self.pushButtonFlash.setObjectName(_fromUtf8("pushButtonFlash"))
        self.gridLayout_2.addWidget(self.pushButtonFlash, 1, 13, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 14, 1, 1)
        self.pushButtonFirmwareRefresh = QtGui.QPushButton(self.frame_4)
        self.pushButtonFirmwareRefresh.setObjectName(_fromUtf8("pushButtonFirmwareRefresh"))
        self.gridLayout_2.addWidget(self.pushButtonFirmwareRefresh, 1, 12, 1, 1)
        self.checkBoxAdb = QtGui.QCheckBox(self.frame_4)
        self.checkBoxAdb.setEnabled(False)
        self.checkBoxAdb.setObjectName(_fromUtf8("checkBoxAdb"))
        self.gridLayout_2.addWidget(self.checkBoxAdb, 0, 8, 1, 1)
        self.checkBoxFastboot = QtGui.QCheckBox(self.frame_4)
        self.checkBoxFastboot.setEnabled(False)
        self.checkBoxFastboot.setObjectName(_fromUtf8("checkBoxFastboot"))
        self.gridLayout_2.addWidget(self.checkBoxFastboot, 0, 9, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.frame_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 15)
        self.label_36 = QtGui.QLabel(self.frame_4)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 0, 1, 1)
        self.pushButtonCheckSum = QtGui.QPushButton(self.frame_4)
        self.pushButtonCheckSum.setObjectName(_fromUtf8("pushButtonCheckSum"))
        self.gridLayout_2.addWidget(self.pushButtonCheckSum, 1, 11, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEditFirmwareDir = QtGui.QLineEdit(self.frame_4)
        self.lineEditFirmwareDir.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditFirmwareDir.setObjectName(_fromUtf8("lineEditFirmwareDir"))
        self.gridLayout_2.addWidget(self.lineEditFirmwareDir, 1, 1, 1, 9)
        self.comboBoxDevList = QtGui.QComboBox(self.frame_4)
        self.comboBoxDevList.setEnabled(False)
        self.comboBoxDevList.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxDevList.setObjectName(_fromUtf8("comboBoxDevList"))
        self.gridLayout_2.addWidget(self.comboBoxDevList, 0, 1, 1, 7)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 14, 1, 1)
        self.pushButton2Fastboot = QtGui.QPushButton(self.frame_4)
        self.pushButton2Fastboot.setObjectName(_fromUtf8("pushButton2Fastboot"))
        self.gridLayout_2.addWidget(self.pushButton2Fastboot, 0, 10, 1, 1)
        self.pushButtonReboot = QtGui.QPushButton(self.frame_4)
        self.pushButtonReboot.setObjectName(_fromUtf8("pushButtonReboot"))
        self.gridLayout_2.addWidget(self.pushButtonReboot, 0, 11, 1, 1)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 16, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.comboBoxBaudrates = QtGui.QComboBox(self.frame)
        self.comboBoxBaudrates.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxBaudrates.setEditable(True)
        self.comboBoxBaudrates.setObjectName(_fromUtf8("comboBoxBaudrates"))
        self.gridLayout_4.addWidget(self.comboBoxBaudrates, 0, 3, 1, 1)
        self.comboBoxParities = QtGui.QComboBox(self.frame)
        self.comboBoxParities.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxParities.setObjectName(_fromUtf8("comboBoxParities"))
        self.gridLayout_4.addWidget(self.comboBoxParities, 0, 9, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 6, 1, 1)
        self.comboBoxStopbits = QtGui.QComboBox(self.frame)
        self.comboBoxStopbits.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxStopbits.setObjectName(_fromUtf8("comboBoxStopbits"))
        self.gridLayout_4.addWidget(self.comboBoxStopbits, 0, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 10, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 8, 1, 1)
        self.comboBoxBytesizes = QtGui.QComboBox(self.frame)
        self.comboBoxBytesizes.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxBytesizes.setObjectName(_fromUtf8("comboBoxBytesizes"))
        self.gridLayout_4.addWidget(self.comboBoxBytesizes, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 4, 1, 1)
        self.TargetIPlabel = QtGui.QLabel(self.frame)
        self.TargetIPlabel.setObjectName(_fromUtf8("TargetIPlabel"))
        self.gridLayout_4.addWidget(self.TargetIPlabel, 0, 0, 1, 1)
        self.comboBoxFlowCtrl = QtGui.QComboBox(self.frame)
        self.comboBoxFlowCtrl.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxFlowCtrl.setObjectName(_fromUtf8("comboBoxFlowCtrl"))
        self.gridLayout_4.addWidget(self.comboBoxFlowCtrl, 0, 11, 1, 1)
        self.comboBoxPorts = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPorts.sizePolicy().hasHeightForWidth())
        self.comboBoxPorts.setSizePolicy(sizePolicy)
        self.comboBoxPorts.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxPorts.setEditable(True)
        self.comboBoxPorts.setObjectName(_fromUtf8("comboBoxPorts"))
        self.gridLayout_4.addWidget(self.comboBoxPorts, 0, 1, 1, 1)
        self.pushButtonOpenSerial = QtGui.QPushButton(self.frame)
        self.pushButtonOpenSerial.setFlat(False)
        self.pushButtonOpenSerial.setObjectName(_fromUtf8("pushButtonOpenSerial"))
        self.gridLayout_4.addWidget(self.pushButtonOpenSerial, 1, 0, 1, 1)
        self.pushButtonCloseSerial = QtGui.QPushButton(self.frame)
        self.pushButtonCloseSerial.setEnabled(False)
        self.pushButtonCloseSerial.setFlat(False)
        self.pushButtonCloseSerial.setObjectName(_fromUtf8("pushButtonCloseSerial"))
        self.gridLayout_4.addWidget(self.pushButtonCloseSerial, 1, 1, 1, 1)
        self.pushButtonRefreshSerial = QtGui.QPushButton(self.frame)
        self.pushButtonRefreshSerial.setEnabled(True)
        self.pushButtonRefreshSerial.setObjectName(_fromUtf8("pushButtonRefreshSerial"))
        self.gridLayout_4.addWidget(self.pushButtonRefreshSerial, 0, 12, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.textBrowserLog = QtGui.QTextBrowser(self.frame_2)
        self.textBrowserLog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.textBrowserLog.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.verticalLayout.addWidget(self.textBrowserLog)
        self.cmdlineEdit = QtGui.QLineEdit(self.frame_2)
        self.cmdlineEdit.setEnabled(False)
        self.cmdlineEdit.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.cmdlineEdit.setObjectName(_fromUtf8("cmdlineEdit"))
        self.verticalLayout.addWidget(self.cmdlineEdit)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButtonFirmwareDir.setText(_translate("MainWindow", "浏览", None))
        self.pushButtonFlash.setText(_translate("MainWindow", "刷入固件", None))
        self.pushButtonFirmwareRefresh.setText(_translate("MainWindow", "刷新固件列表", None))
        self.checkBoxAdb.setText(_translate("MainWindow", "Adb", None))
        self.checkBoxFastboot.setText(_translate("MainWindow", "Fastboot", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "路径", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "版本", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "校验状态", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "耗时", None))
        self.label_36.setText(_translate("MainWindow", "当前连接设备：", None))
        self.pushButtonCheckSum.setText(_translate("MainWindow", "校验", None))
        self.label_14.setText(_translate("MainWindow", "固件路径：", None))
        self.pushButton2Fastboot.setText(_translate("MainWindow", "进入Fastboot", None))
        self.pushButtonReboot.setText(_translate("MainWindow", "重启", None))
        self.label.setText(_translate("MainWindow", "波特率：", None))
        self.label_10.setText(_translate("MainWindow", "停止位：", None))
        self.label_15.setText(_translate("MainWindow", "流控制：", None))
        self.label_2.setText(_translate("MainWindow", "校验位：", None))
        self.label_3.setText(_translate("MainWindow", "数据位：", None))
        self.TargetIPlabel.setText(_translate("MainWindow", "串口：", None))
        self.pushButtonOpenSerial.setText(_translate("MainWindow", "打开", None))
        self.pushButtonCloseSerial.setText(_translate("MainWindow", "关闭", None))
        self.pushButtonRefreshSerial.setText(_translate("MainWindow", "刷新", None))
        self.textBrowserLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.actionExit.setText(_translate("MainWindow", "退出", None))

