# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(816, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_4 = QtGui.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.frame_4)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setAccessibleName(_fromUtf8(""))
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabInfo)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonRefreshInfo = QtGui.QPushButton(self.tabInfo)
        self.pushButtonRefreshInfo.setObjectName(_fromUtf8("pushButtonRefreshInfo"))
        self.horizontalLayout_2.addWidget(self.pushButtonRefreshInfo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.textBrowserInfo = QtGui.QTextBrowser(self.tabInfo)
        self.textBrowserInfo.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserInfo.setStyleSheet(_fromUtf8("border: none;\n"
"font: 9pt \"Consolas\";"))
        self.textBrowserInfo.setObjectName(_fromUtf8("textBrowserInfo"))
        self.verticalLayout_4.addWidget(self.textBrowserInfo)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabServerSetting = QtGui.QWidget()
        self.tabServerSetting.setObjectName(_fromUtf8("tabServerSetting"))
        self.formLayoutWidget = QtGui.QWidget(self.tabServerSetting)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 181))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.Label = QtGui.QLabel(self.formLayoutWidget)
        self.Label.setObjectName(_fromUtf8("Label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Label)
        self.LineEditOperationIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditOperationIp.setObjectName(_fromUtf8("LineEditOperationIp"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEditOperationIp)
        self.Label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_2)
        self.LineEditOperationPort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditOperationPort.setObjectName(_fromUtf8("LineEditOperationPort"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LineEditOperationPort)
        self.Label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_3.setObjectName(_fromUtf8("Label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Label_3)
        self.LineEditUpdateIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditUpdateIp.setObjectName(_fromUtf8("LineEditUpdateIp"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LineEditUpdateIp)
        self.Label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_4.setObjectName(_fromUtf8("Label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.Label_4)
        self.LineEditUpdatePort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditUpdatePort.setObjectName(_fromUtf8("LineEditUpdatePort"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LineEditUpdatePort)
        self.LineEditIdCardIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditIdCardIp.setObjectName(_fromUtf8("LineEditIdCardIp"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.LineEditIdCardIp)
        self.LineEditIdCardPort = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditIdCardPort.setObjectName(_fromUtf8("LineEditIdCardPort"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.LineEditIdCardPort)
        self.Label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_6.setObjectName(_fromUtf8("Label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.Label_6)
        self.Label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.Label_5.setObjectName(_fromUtf8("Label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.Label_5)
        self.uRLLabel = QtGui.QLabel(self.formLayoutWidget)
        self.uRLLabel.setObjectName(_fromUtf8("uRLLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.uRLLabel)
        self.LineEditLogURL = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditLogURL.setObjectName(_fromUtf8("LineEditLogURL"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.LineEditLogURL)
        self.pushButtonSaveServer = QtGui.QPushButton(self.tabServerSetting)
        self.pushButtonSaveServer.setGeometry(QtCore.QRect(590, 200, 75, 23))
        self.pushButtonSaveServer.setObjectName(_fromUtf8("pushButtonSaveServer"))
        self.pushButtonRefreshServer = QtGui.QPushButton(self.tabServerSetting)
        self.pushButtonRefreshServer.setGeometry(QtCore.QRect(500, 200, 75, 23))
        self.pushButtonRefreshServer.setObjectName(_fromUtf8("pushButtonRefreshServer"))
        self.tabWidget.addTab(self.tabServerSetting, _fromUtf8(""))
        self.tabNetSetting = QtGui.QWidget()
        self.tabNetSetting.setObjectName(_fromUtf8("tabNetSetting"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabNetSetting)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tabNetSetting)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonWanStatic = QtGui.QRadioButton(self.groupBox)
        self.radioButtonWanStatic.setGeometry(QtCore.QRect(19, 48, 47, 16))
        self.radioButtonWanStatic.setChecked(True)
        self.radioButtonWanStatic.setObjectName(_fromUtf8("radioButtonWanStatic"))
        self.pushButtonWanRefresh = QtGui.QPushButton(self.groupBox)
        self.pushButtonWanRefresh.setGeometry(QtCore.QRect(80, 170, 75, 23))
        self.pushButtonWanRefresh.setObjectName(_fromUtf8("pushButtonWanRefresh"))
        self.pushButtonWanSave = QtGui.QPushButton(self.groupBox)
        self.pushButtonWanSave.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButtonWanSave.setObjectName(_fromUtf8("pushButtonWanSave"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(19, 78, 36, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEditWanIp = QtGui.QLineEdit(self.groupBox)
        self.lineEditWanIp.setGeometry(QtCore.QRect(100, 78, 133, 20))
        self.lineEditWanIp.setObjectName(_fromUtf8("lineEditWanIp"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(19, 104, 48, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEditWanMask = QtGui.QLineEdit(self.groupBox)
        self.lineEditWanMask.setGeometry(QtCore.QRect(100, 104, 133, 20))
        self.lineEditWanMask.setObjectName(_fromUtf8("lineEditWanMask"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(19, 130, 48, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEditWanGateway = QtGui.QLineEdit(self.groupBox)
        self.lineEditWanGateway.setGeometry(QtCore.QRect(100, 130, 133, 20))
        self.lineEditWanGateway.setObjectName(_fromUtf8("lineEditWanGateway"))
        self.radioButtonWanAuto = QtGui.QRadioButton(self.groupBox)
        self.radioButtonWanAuto.setGeometry(QtCore.QRect(100, 48, 71, 16))
        self.radioButtonWanAuto.setObjectName(_fromUtf8("radioButtonWanAuto"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.labelWanName = QtGui.QLabel(self.groupBox)
        self.labelWanName.setGeometry(QtCore.QRect(100, 21, 54, 12))
        self.labelWanName.setObjectName(_fromUtf8("labelWanName"))
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabNetSetting)
        self.groupBox_2.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButtonLanSave = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonLanSave.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButtonLanSave.setObjectName(_fromUtf8("pushButtonLanSave"))
        self.pushButtonLanRefresh = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonLanRefresh.setGeometry(QtCore.QRect(80, 170, 75, 23))
        self.pushButtonLanRefresh.setObjectName(_fromUtf8("pushButtonLanRefresh"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 48, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditLanMask = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditLanMask.setGeometry(QtCore.QRect(100, 95, 133, 20))
        self.lineEditLanMask.setObjectName(_fromUtf8("lineEditLanMask"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 36, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditLanIp = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditLanIp.setGeometry(QtCore.QRect(100, 70, 133, 20))
        self.lineEditLanIp.setObjectName(_fromUtf8("lineEditLanIp"))
        self.labelLanName = QtGui.QLabel(self.groupBox_2)
        self.labelLanName.setGeometry(QtCore.QRect(100, 22, 54, 12))
        self.labelLanName.setObjectName(_fromUtf8("labelLanName"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 21, 54, 12))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabNetSetting, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textBrowserLog = QtGui.QTextBrowser(self.frame_2)
        self.textBrowserLog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.textBrowserLog.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.verticalLayout.addWidget(self.textBrowserLog)
        self.cmdlineEdit = QtGui.QLineEdit(self.frame_2)
        self.cmdlineEdit.setEnabled(False)
        self.cmdlineEdit.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.cmdlineEdit.setObjectName(_fromUtf8("cmdlineEdit"))
        self.verticalLayout.addWidget(self.cmdlineEdit)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.TargetIPlabel = QtGui.QLabel(self.frame)
        self.TargetIPlabel.setObjectName(_fromUtf8("TargetIPlabel"))
        self.horizontalLayout.addWidget(self.TargetIPlabel)
        self.lineEditIp = QtGui.QLineEdit(self.frame)
        self.lineEditIp.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditIp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditIp.setObjectName(_fromUtf8("lineEditIp"))
        self.horizontalLayout.addWidget(self.lineEditIp)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditPort = QtGui.QLineEdit(self.frame)
        self.lineEditPort.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditPort.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.horizontalLayout.addWidget(self.lineEditPort)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditUsername = QtGui.QLineEdit(self.frame)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.horizontalLayout.addWidget(self.lineEditUsername)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditPassword = QtGui.QLineEdit(self.frame)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditPassword.setStyleSheet(_fromUtf8("lineedit-password-character: 42"))
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.horizontalLayout.addWidget(self.lineEditPassword)
        self.pushButtonConnect = QtGui.QPushButton(self.frame)
        self.pushButtonConnect.setFlat(False)
        self.pushButtonConnect.setObjectName(_fromUtf8("pushButtonConnect"))
        self.horizontalLayout.addWidget(self.pushButtonConnect)
        self.pushButtonReboot = QtGui.QPushButton(self.frame)
        self.pushButtonReboot.setEnabled(False)
        self.pushButtonReboot.setObjectName(_fromUtf8("pushButtonReboot"))
        self.horizontalLayout.addWidget(self.pushButtonReboot)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButtonRefreshInfo.setText(_translate("MainWindow", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("MainWindow", "信息", None))
        self.Label.setText(_translate("MainWindow", "业务服务器地址", None))
        self.Label_2.setText(_translate("MainWindow", "业务服务器端口", None))
        self.Label_3.setText(_translate("MainWindow", "升级服务器地址", None))
        self.Label_4.setText(_translate("MainWindow", "升级服务器端口", None))
        self.Label_6.setText(_translate("MainWindow", "身份证服务器端口", None))
        self.Label_5.setText(_translate("MainWindow", "身份证服务器地址", None))
        self.uRLLabel.setText(_translate("MainWindow", "日志服务URL", None))
        self.pushButtonSaveServer.setText(_translate("MainWindow", "保存", None))
        self.pushButtonRefreshServer.setText(_translate("MainWindow", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServerSetting), _translate("MainWindow", "服务器配置", None))
        self.groupBox.setTitle(_translate("MainWindow", "WAN", None))
        self.radioButtonWanStatic.setText(_translate("MainWindow", "静态", None))
        self.pushButtonWanRefresh.setText(_translate("MainWindow", "刷新", None))
        self.pushButtonWanSave.setText(_translate("MainWindow", "保存", None))
        self.label_4.setText(_translate("MainWindow", "IP地址", None))
        self.label_6.setText(_translate("MainWindow", "子网掩码", None))
        self.label_5.setText(_translate("MainWindow", "默认网关", None))
        self.radioButtonWanAuto.setText(_translate("MainWindow", "自动获取", None))
        self.label_9.setText(_translate("MainWindow", "设备名称", None))
        self.labelWanName.setText(_translate("MainWindow", "________", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "LAN", None))
        self.pushButtonLanSave.setText(_translate("MainWindow", "保存", None))
        self.pushButtonLanRefresh.setText(_translate("MainWindow", "刷新", None))
        self.label_8.setText(_translate("MainWindow", "子网掩码", None))
        self.label_7.setText(_translate("MainWindow", "IP地址", None))
        self.labelLanName.setText(_translate("MainWindow", "________", None))
        self.label_12.setText(_translate("MainWindow", "设备名称", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNetSetting), _translate("MainWindow", "网络配置", None))
        self.textBrowserLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.TargetIPlabel.setText(_translate("MainWindow", "设备IP：", None))
        self.lineEditIp.setText(_translate("MainWindow", "172.16.34.111", None))
        self.label.setText(_translate("MainWindow", "端口：", None))
        self.lineEditPort.setText(_translate("MainWindow", "22", None))
        self.label_2.setText(_translate("MainWindow", "用户名：", None))
        self.lineEditUsername.setText(_translate("MainWindow", "root", None))
        self.label_3.setText(_translate("MainWindow", "密码：", None))
        self.lineEditPassword.setText(_translate("MainWindow", "t0d7r19tdr", None))
        self.pushButtonConnect.setText(_translate("MainWindow", "连接", None))
        self.pushButtonReboot.setText(_translate("MainWindow", "重启", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.actionExit.setText(_translate("MainWindow", "退出", None))

