# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(879, 575)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, 9, 9, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_4 = QtGui.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_7 = QtGui.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_36 = QtGui.QLabel(self.frame_7)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.comboBoxDevList = QtGui.QComboBox(self.frame_7)
        self.comboBoxDevList.setMinimumSize(QtCore.QSize(160, 0))
        self.comboBoxDevList.setObjectName(_fromUtf8("comboBoxDevList"))
        self.horizontalLayout_6.addWidget(self.comboBoxDevList)
        self.pushButtonRefreshDev = QtGui.QPushButton(self.frame_7)
        self.pushButtonRefreshDev.setObjectName(_fromUtf8("pushButtonRefreshDev"))
        self.horizontalLayout_6.addWidget(self.pushButtonRefreshDev)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.tabWidget = QtGui.QTabWidget(self.frame_4)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setAccessibleName(_fromUtf8(""))
        self.tabInfo.setObjectName(_fromUtf8("tabInfo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabInfo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.tabInfo)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.tabInfo)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tabInfo)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 11)
        self.pushButton = QtGui.QPushButton(self.tabInfo)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 1, 4, 1, 1)
        self.labelDevState = QtGui.QLabel(self.tabInfo)
        self.labelDevState.setObjectName(_fromUtf8("labelDevState"))
        self.gridLayout_2.addWidget(self.labelDevState, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabInfo)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tabInfo)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.pushButton_8 = QtGui.QPushButton(self.tabInfo)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 9, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tabInfo)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tabInfo)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 7, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tabInfo)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tabInfo, _fromUtf8(""))
        self.tabServerSetting = QtGui.QWidget()
        self.tabServerSetting.setObjectName(_fromUtf8("tabServerSetting"))
        self.tabWidget.addTab(self.tabServerSetting, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 16, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.comboBoxBaudrates = QtGui.QComboBox(self.frame)
        self.comboBoxBaudrates.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxBaudrates.setEditable(True)
        self.comboBoxBaudrates.setObjectName(_fromUtf8("comboBoxBaudrates"))
        self.gridLayout_4.addWidget(self.comboBoxBaudrates, 0, 3, 1, 1)
        self.comboBoxParities = QtGui.QComboBox(self.frame)
        self.comboBoxParities.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxParities.setObjectName(_fromUtf8("comboBoxParities"))
        self.gridLayout_4.addWidget(self.comboBoxParities, 0, 9, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 6, 1, 1)
        self.comboBoxStopbits = QtGui.QComboBox(self.frame)
        self.comboBoxStopbits.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxStopbits.setObjectName(_fromUtf8("comboBoxStopbits"))
        self.gridLayout_4.addWidget(self.comboBoxStopbits, 0, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 10, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 8, 1, 1)
        self.comboBoxBytesizes = QtGui.QComboBox(self.frame)
        self.comboBoxBytesizes.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxBytesizes.setObjectName(_fromUtf8("comboBoxBytesizes"))
        self.gridLayout_4.addWidget(self.comboBoxBytesizes, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 4, 1, 1)
        self.TargetIPlabel = QtGui.QLabel(self.frame)
        self.TargetIPlabel.setObjectName(_fromUtf8("TargetIPlabel"))
        self.gridLayout_4.addWidget(self.TargetIPlabel, 0, 0, 1, 1)
        self.comboBoxFlowCtrl = QtGui.QComboBox(self.frame)
        self.comboBoxFlowCtrl.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxFlowCtrl.setObjectName(_fromUtf8("comboBoxFlowCtrl"))
        self.gridLayout_4.addWidget(self.comboBoxFlowCtrl, 0, 11, 1, 1)
        self.comboBoxPorts = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPorts.sizePolicy().hasHeightForWidth())
        self.comboBoxPorts.setSizePolicy(sizePolicy)
        self.comboBoxPorts.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBoxPorts.setEditable(True)
        self.comboBoxPorts.setObjectName(_fromUtf8("comboBoxPorts"))
        self.gridLayout_4.addWidget(self.comboBoxPorts, 0, 1, 1, 1)
        self.pushButtonOpenSerial = QtGui.QPushButton(self.frame)
        self.pushButtonOpenSerial.setFlat(False)
        self.pushButtonOpenSerial.setObjectName(_fromUtf8("pushButtonOpenSerial"))
        self.gridLayout_4.addWidget(self.pushButtonOpenSerial, 1, 0, 1, 1)
        self.pushButtonCloseSerial = QtGui.QPushButton(self.frame)
        self.pushButtonCloseSerial.setEnabled(False)
        self.pushButtonCloseSerial.setFlat(False)
        self.pushButtonCloseSerial.setObjectName(_fromUtf8("pushButtonCloseSerial"))
        self.gridLayout_4.addWidget(self.pushButtonCloseSerial, 1, 1, 1, 1)
        self.pushButtonRefreshSerial = QtGui.QPushButton(self.frame)
        self.pushButtonRefreshSerial.setEnabled(True)
        self.pushButtonRefreshSerial.setObjectName(_fromUtf8("pushButtonRefreshSerial"))
        self.gridLayout_4.addWidget(self.pushButtonRefreshSerial, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.textBrowserLog = QtGui.QTextBrowser(self.frame_2)
        self.textBrowserLog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.textBrowserLog.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.verticalLayout.addWidget(self.textBrowserLog)
        self.cmdlineEdit = QtGui.QLineEdit(self.frame_2)
        self.cmdlineEdit.setEnabled(False)
        self.cmdlineEdit.setStyleSheet(_fromUtf8("font: 9pt \"Consolas\";"))
        self.cmdlineEdit.setObjectName(_fromUtf8("cmdlineEdit"))
        self.verticalLayout.addWidget(self.cmdlineEdit)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_36.setText(_translate("MainWindow", "当前连接设备：", None))
        self.pushButtonRefreshDev.setText(_translate("MainWindow", "刷新", None))
        self.pushButton_4.setText(_translate("MainWindow", "校验", None))
        self.label_14.setText(_translate("MainWindow", "固件路径：", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "名称", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "版本", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "校验状态", None))
        self.pushButton.setText(_translate("MainWindow", "浏览", None))
        self.labelDevState.setText(_translate("MainWindow", "Device/Fastboot", None))
        self.label_11.setText(_translate("MainWindow", "连接状态：", None))
        self.pushButton_8.setText(_translate("MainWindow", "刷入固件", None))
        self.pushButton_7.setText(_translate("MainWindow", "重启", None))
        self.pushButton_3.setText(_translate("MainWindow", "重启进入Fastboot", None))
        self.pushButton_2.setText(_translate("MainWindow", "刷新固件列表", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("MainWindow", "刷机", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServerSetting), _translate("MainWindow", "服务器配置", None))
        self.label.setText(_translate("MainWindow", "波特率：", None))
        self.label_10.setText(_translate("MainWindow", "停止位：", None))
        self.label_15.setText(_translate("MainWindow", "流控制：", None))
        self.label_2.setText(_translate("MainWindow", "校验位：", None))
        self.label_3.setText(_translate("MainWindow", "数据位：", None))
        self.TargetIPlabel.setText(_translate("MainWindow", "串口：", None))
        self.pushButtonOpenSerial.setText(_translate("MainWindow", "打开", None))
        self.pushButtonCloseSerial.setText(_translate("MainWindow", "关闭", None))
        self.pushButtonRefreshSerial.setText(_translate("MainWindow", "刷新", None))
        self.textBrowserLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.actionExit.setText(_translate("MainWindow", "退出", None))

